# Copyright (c) The dgc.network
# SPDX-License-Identifier: Apache-2.0

version: '2.1'

services:
  dgc-wallet-rust-processor:
    container_name: dgc-wallet-rust-processor
    build:
      context: .
      dockerfile: ./rustprocessor/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - 'http_proxy=${http_proxy}'
      - 'https_proxy=${https_proxy}'
      - 'no_proxy=rest-api,validator,${no_proxy}'
    depends_on:
      - validator
    volumes:
      - '.:/project/dgc-wallet/'

  dgc-wallet-rest-api:
    container_name: dgc-wallet-rest-api
    build:
      context: .
      dockerfile: ./jsclient/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - 'http_proxy=${http_proxy}'
      - 'https_proxy=${https_proxy}'
      - 'no_proxy=rest-api,validator,${no_proxy}'
    volumes:
      - '.:/project/dgc-wallet/'
    ports:
      - '0.0.0.0:3000:3000'
    depends_on:
      - sawtooth-rest-api
    stop_signal: SIGKILL

  sawtooth-rest-api:
    container_name: rest-api
    image: hyperledger/sawtooth-rest-api:1.0
    expose:
      - 8008
    ports:
      - '8008:8008'
    depends_on:
      - validator
    entrypoint: |
      sawtooth-rest-api -vvv
        --connect tcp://validator:4004
        --bind sawtooth-rest-api:8008

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    depends_on:
      - validator
    command: settings-tp -vv --connect tcp://validator:4004

  validator:
    container_name: validator
    image: hyperledger/sawtooth-validator:1.0
    expose:
      - 4004
    ports:
      - '4004:4004'
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
        sawadm keygen &&
        sawtooth keygen my_key &&
        sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
        sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator -vvv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
      "
